// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppLoadSettings() {
  return window['go']['main']['App']['AppLoadSettings']();
}

export function AppSaveSettings(arg1) {
  return window['go']['main']['App']['AppSaveSettings'](arg1);
}

export function CreateTorrent(arg1) {
  return window['go']['main']['App']['CreateTorrent'](arg1);
}

export function DownloadTorrent(arg1) {
  return window['go']['main']['App']['DownloadTorrent'](arg1);
}

export function GenerateNFO(arg1, arg2) {
  return window['go']['main']['App']['GenerateNFO'](arg1, arg2);
}

export function GetMediaInfo(arg1) {
  return window['go']['main']['App']['GetMediaInfo'](arg1);
}

export function GetTMDBDetails(arg1, arg2) {
  return window['go']['main']['App']['GetTMDBDetails'](arg1, arg2);
}

export function ReadTextFile(arg1) {
  return window['go']['main']['App']['ReadTextFile'](arg1);
}

export function SearchTMDB(arg1, arg2) {
  return window['go']['main']['App']['SearchTMDB'](arg1, arg2);
}

export function SelectDirectory(arg1) {
  return window['go']['main']['App']['SelectDirectory'](arg1);
}

export function SelectFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SelectFile'](arg1, arg2, arg3);
}

export function UploadTorrent(arg1) {
  return window['go']['main']['App']['UploadTorrent'](arg1);
}
